name: CICD

on: 
  workflow_dispatch:
    inputs:
      environment:
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Code clone from GitHub"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container Build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the Container
        run: echo "Testing the Container"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
